language: ruby
rvm:
  - 2.2.1
addons:
  postgresql: '9.3'
before_install:
  - openssl aes-256-cbc -K $encrypted_e28298503a52_key -iv $encrypted_e28298503a52_iv -in config/secrets.yml.enc -out config/secrets.yml -d
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
 # - cp config/secrets.yml.travis config/secrets.yml
  - cp config/initializers/secret_token.rb.travis config/initializers/secret_token.rb
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
